### SECP 3223 PROJECT PHASE 1

STUDENT INFO:
1) Name:
- NUR FIRZANA BINTI BADRUS HISHAM (A23CS0156)
- NURUL ADRIANA BINTI KAMAL JEFRI (A23CS0258)
- Harini A/P Sangaran (A23CS0081)
2) Section: 02

In [1]:
import pandas as pd

In [7]:
fuel_df = pd.read_csv('FuelConsumption.csv')
cars_df = pd.read_csv('cars_2025.csv')

fuel_df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [8]:
cars_df.head()

     date_reg        type  maker      model  colour         fuel        state
0  2025-01-01     motokar    BYD       Seal   white     electric  Rakan Niaga
1  2025-01-01  window_van    Cam   Placer-X  yellow  greendiesel        Johor
2  2025-01-01         jip  Chery  Jaecoo J7   green       petrol  Rakan Niaga
3  2025-01-01         jip  Chery  Jaecoo J7  silver       petrol  Rakan Niaga
4  2025-01-01         jip  Chery      Tiggo    grey       petrol  Rakan Niaga

In [10]:
fuel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   MODELYEAR                 1067 non-null   int64
 1   MAKE                      1067 non-null   object
 2   MODEL                     1067 non-null   object
 3   VEHICLECLASS              1067 non-null   object
 4   ENGINESIZE                1067 non-null   float64
 5   CYLINDERS                 1067 non-null   int64
 6   TRANSMISSION              1067 non-null   object
 7   FUELTYPE                  1067 non-null   object
 8   FUELCONSUMPTION_CITY      1067 non-null   float64
 9   FUELCONSUMPTION_HWY       1067 non-null   float64
 10  FUELCONSUMPTION_COMB      1067 non-null   float64
 11  FUELCONSUMPTION_COMB_MPG  1067 non-null   int64
 12  CO2EMISSIONS              1067 non-null   int64
dtypes: float64(4), int64(4), object(5)
memory usage: 108.5+ KB

In [11]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263578 entries, 0 to 263577
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   date_reg  263578 non-null  object
 1   type      263578 non-null  object
 2   maker     263578 non-null  object
 3   model     263578 non-null  object
 4   colour    263578 non-null  object
 5   fuel      263578 non-null  object
 6   state     263578 non-null  object
dtypes: object(7)
memory usage: 14.1+ MB